### ISSUE TITLE
Missing script gpu_metrics_collector.py 

### ISSUE THREAD

**Issue by entrepeneur4lyf** [chrisbraddock/gpu-tune#1]
```
def start_gpu_metrics_collector(interval=10, log_file='gpu_metrics_log.csv'):
    command = f"python gpu_metrics_collector.py --interval {interval} --log_file {log_file}"
    process = subprocess.Popen(command, shell=True)
    return process
```

This method refers to gpu_metrics_collector.py that doesn't exist in the project

**Comment by chrisbraddock** [comment]
> This method refers to gpu_metrics_collector.py that doesn't exist in the project

Thanks. That shouldn't be referenced anymore. GPU metrics are collected at the same time/as part of the same data as inference/training now.

I'll remove this shortly.
